version: "3.9"

services:
  db:
    image: postgres:latest    # utilise ton image locale
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: signalement_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: travaux-web:latest  # utilise ton image locale
    container_name: spring_app_travaux
    ports:
      - "8085:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/signalement_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
